"""add strategy_label to interactions

Revision ID: 1e910caaa9ac
Revises: 915dc6f08280
Create Date: 2026-10-07 09:37:39.453234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e910caaa9ac'
down_revision: Union[str, Sequence[str], None] = '915dc6f08280'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interactions', sa.Column('strategy_label', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interactions', 'strategy_label')
    # ### end Alembic commands ###
