"""add_sessions_and_interactions_tables

Revision ID: 915dc6f08280
Revises: c7b7975bec35
Create Date: 2026-10-07 09:24:15.200577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '915dc6f08280'
down_revision: Union[str, Sequence[str], None] = 'c7b7975bec35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('topic_id', sa.String(length=36), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_sessions_student_id'), 'learning_sessions', ['student_id'], unique=False)
    op.create_index(op.f('ix_learning_sessions_subject_id'), 'learning_sessions', ['subject_id'], unique=False)
    op.create_index(op.f('ix_learning_sessions_topic_id'), 'learning_sessions', ['topic_id'], unique=False)
    op.create_table('interactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('student_message', sa.Text(), nullable=False),
    sa.Column('ai_response', sa.Text(), nullable=False),
    sa.Column('agent_action', sa.String(length=50), nullable=False),
    sa.Column('grounded', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['learning_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interactions_session_id'), 'interactions', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interactions_session_id'), table_name='interactions')
    op.drop_table('interactions')
    op.drop_index(op.f('ix_learning_sessions_topic_id'), table_name='learning_sessions')
    op.drop_index(op.f('ix_learning_sessions_subject_id'), table_name='learning_sessions')
    op.drop_index(op.f('ix_learning_sessions_student_id'), table_name='learning_sessions')
    op.drop_table('learning_sessions')
    # ### end Alembic commands ###
